const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const drawer=$('#mobileDrawer'), backdrop=$('#drawerBackdrop'), menu=$('#menuButton');
function openDrawer(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;menu.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');backdrop.hidden=true;menu.setAttribute('aria-expanded','false');document.body.style.overflow=''}
menu.addEventListener('click',openDrawer);$('#drawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);$$('.mobile-drawer a').forEach(a=>a.addEventListener('click',closeDrawer));
$$('.course-tabs button').forEach(btn=>btn.addEventListener('click',()=>{ $$('.course-tabs button').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const f=btn.dataset.filter; $$('.course-card').forEach(c=>c.style.display=(f==='all'||c.dataset.type===f)?'block':'none'); }));
const lightbox=$('#lightbox'), lightboxImage=$('#lightboxImage');$$('.gallery-grid button').forEach(b=>b.addEventListener('click',()=>{lightboxImage.src=b.dataset.image;lightbox.hidden=false;document.body.style.overflow='hidden'}));$('#lightboxClose').addEventListener('click',()=>{lightbox.hidden=true;document.body.style.overflow=''});lightbox.addEventListener('click',e=>{if(e.target===lightbox){lightbox.hidden=true;document.body.style.overflow=''}});
const lineMessage='您好，我想洽詢朱老師 AI 圍棋課程。';function openLine(e){e.preventDefault();window.location.href='https://line.me/R/msg/text/?'+encodeURIComponent(lineMessage)}$('#dockLine').addEventListener('click',openLine);$('#lineTop').addEventListener('click',openLine);
$('#dockToggle').addEventListener('click',()=>{const items=$('#dockItems');const closed=items.classList.toggle('closed');$('#dockToggle').setAttribute('aria-expanded',String(!closed));$('#dockToggle').textContent=closed?'展開':'聯絡';});
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();const text=`朱老師您好，我想報名／洽詢課程\n姓名：${$('#name').value}\n電話：${$('#phone').value}\nLINE：${$('#lineName').value||'未填'}\n目前棋力：${$('#level').value}\n課程需求：${$('#course').value}\n其他需求：${$('#message').value||'無'}`;try{await navigator.clipboard.writeText(text);$('#formStatus').textContent='報名內容已複製，可貼到 LINE 或簡訊。'}catch{$('#formStatus').textContent=text}});
const topBtn=$('#backToTop');window.addEventListener('scroll',()=>topBtn.classList.toggle('show',window.scrollY>500));topBtn.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));$('#year').textContent=new Date().getFullYear();
